### PR TITLE
Create note2.txt

### PR DESCRIPTION
**Pull request by monsij98**
Add note2.txt

### CODE REVIEW

**Comment by monsij** [comment]
Hope you have read the contribution guidelines before opening the PR

(Powered by [GitMate.io](https://gitmate.io))

**Comment by monsij98** [comment]
"@gitmate-bot rebase"

**Comment by monsij** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by monsij** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
